### PR TITLE
Add Google Scholar Save All

### PR DESCRIPTION
**Pull request by asmpro7**

### CODE REVIEW

**Review by adamlui — CHANGES_REQUESTED** [review]
Hey  I installed in Tampermonkey for FF but the button doesn't appear

image

**Comment by asmpro7** [comment]
what is the problem with it? 
it appears normally in my browser 
I think is there problem in selector
can you check it in your browser? 
div which include results time in top of results.

**Comment by asmpro7** [comment]
Can you check if you enable it? 
because its work
If it still doesnt work please send html file for the page

**Comment by adamlui** [comment]
> Can you check if you enable it? because its work

Yes it is enabled and doesn't work
image

> If it still doesnt work please send html file for the page

Sorry sir I cannot devote my unpaid time to troubleshoot your broken script when I have so many of my own to maintain already. (If you want exposure for yourself you should fix it not me, I gave you env already)

**Comment by asmpro7** [comment]
Ok sir
I still don't know what's the problem of the script with you. 
I made it only to save my time and think of sharing it with others, It will be useful. 
If my PR is not welcoming, no problem anyone still installing it from greasy fork. 
have a nice day.

**Comment by adamlui** [comment]
A PR is welcome but if it doesn't work then it's not Awesome, if you make it work then I will merge

>  I still don't know what's the problem of the script with you.

The problem is it doesn't work as advertised, your advertisement is "Add a button" but my screenshot proves no button is added, so it ccannot be an Awesome script if it doesn't work

**Comment by adamlui** [comment]
You're the author not me and you ask me to troubleshoot your new project so I feature it in this repo for you, you don't realize that is very strange request? Why would I do that instead of work on my own projects? It is yours not mine, so you should do the hard work for it to be featured and shared by ensuring it at least works as advertised, no one else will do your work for you

**Comment by asmpro7** [comment]
I am with you that is my work, But I need some details on why it doesn't work to modify it. 
one day I will work on it, thanks for notifying me.

**Comment by adamlui** [comment]
You're welcome for the thanks, the detail is I use Firefox Tampermonkey, your 1st step is probably install Firefox Tampermonkey then try it out

**Pull request closed without merging**
